name: webspark
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.1

dependencies:
  dio: ^5.11.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  get_it: ^9.3.0
  injectable: ^3.0.0
  json_annotation: ^4.12.0
  reactive_forms: ^18.2.2
  retrofit: ^4.10.0
  shared_preferences: ^2.5.5
  talker_bloc_logger: ^5.1.20
  talker_dio_logger: ^5.1.20
  talker_flutter: ^5.1.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.5
  build_runner: ^2.15.1
  json_serializable: ^6.14.1
  injectable_generator: ^3.0.2
  retrofit_generator: ^10.2.9

flutter:
  uses-material-design: true
